name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy
  pull_request:
    branches:
      - main  # Set this to the branch you want to deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # You can specify any other runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # Or yarn install, if you use Yarn

      - name: Build
        run: npm run build  # Or your custom build command

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_SEA_03D4D5310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          action: "upload"
          #### Add your specific project settings below ####
          app_location: "/"        # Location of your frontend code
          api_location: "api"      # Location of your API code if applicable
          output_location: "build" # Build output directory

      - name: Expose API key to the app
        run: echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" >> $GITHUB_ENV
        shell: bash

      # Include any other deployment or post-deployment steps here
